version: '3.8'

services:
  back:
    container_name: back
    build: 
      context: .
      dockerfile: back.dockerfile
    tty: true
    ports:
        - "8080:8080"
    depends_on:
        - db
    volumes:
      - .:/back

  db:
    container_name: db
    build: 
      context: .
      dockerfile: db.dockerfile
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "shin"
      MYSQL_PASSWORD: "password"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    networks:
      - default

networks:
  default:
volumes:
  mysql_data: